name: Unit Test Generation Workflow
on: push
jobs:
  unit-test-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Unit Test Generator
        uses: olympix/unit-test-generator@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
