name: Unit Test Generation Workflow
on: push
jobs:
  unit-test-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: show repository id
        run: echo "REPOSITORY ID $GITHUB_REPOSITORY_ID"

      
