name: Unit Test Generation Workflow
on: push
jobs:
  unit-test-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Show repository
        run: echo "Repository owner $GITHUB_REPOSITORY_OWNER and name ${{ github.event.repository.name }}"
