name: Unit Test Generation Workflow
on: push
jobs:
  unit-test-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Show repository
        run: echo "Repsoitory name $GITHUB_REPOSITORY"
